name: CompareRuns

on: 
  pull_request:
    types: [opened, edited, reopened]
  issue_comment:
    types: [submitted, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:

  compare-runs:
      # this filters for only comments made on a pull request
      if: (github.event.issue.pull_request != null)

      runs-on: ubuntu-latest

      env:

        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

        WANDB_ENTITY: ${{ vars.WANDB_ENTITY }}
        WANDB_PROJECT: ${{ vars.WANDB_PROJECT }}
        WANDB_CMD: ${{ vars.WANDB_CMD }}
        BASELINE_TAG: ${{ vars.BASELINE_TAG }}

        PR_COMMENT: ${{ github.event.comment.body }}

      steps:
      
      - name: filter for wandb command
        id: filter
        if: contains(github.event.comment.body, env.WANDB_CMD)
        run: echo "wandb command detected"

      - name: Parse value from the wandb command
        if: steps.filter.outcome == 'success'
        id: get-wandb-value
        shell: python
        run: |
          import re, os
          command = os.environ['WANDB_CMD']
          comment = os.environ['PR_COMMENT']
          match = re.search(f'{command}[\s+](\S+)', comment)
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            if match:
              print(f'VAL_FOUND=true', file=f)
              print(f'WANDB_VAL={match.group(1)}', file=f)
            else:
              print(f'VAL_FOUND=false', file=f)

      - name: checkout repo
        if: steps.get-wandb-value.outcome == 'success' && steps.get-wandb-value.outputs.VAL_FOUND == 'true'
        id: checkout-repo
        uses: actions/checkout@v3

      - name: install dependencies
        if: steps.checkout-repo.outcome == 'success'
        id: install-dependencies
        run: pip install -r requirements.txt

      - name: Create report for comparison
        if:  steps.install-dependencies.outcome == 'success'
        id: create-report
        env:
          WANDB_RUN_ID: ${{ steps.get-wandb-value.outputs.WANDB_VAL }}
        run: python create_report.py --entity $WANDB_ENTITY --project $WANDB_PROJECT --run_id $WANDB_RUN_ID --baseline_tag $BASELINE_TAG

      - name: Create a comment with report url
        uses: actions/github-script@v6
        if:  steps.create-report.outcome == 'success'
        id: create-comment-with-report-url
        with:
          script: |
            var msg = `👋 Hello!  You commented on this PR with a wandb value of \`${process.env.WANDB_VAL}\` \nHere is the <a href="${process.env.WANDB_REPORT_URL}" target="_blank" rel="noopener noreferrer">link to the report</a>.`
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: msg
              })
        env:
          WANDB_VAL: "${{ steps.get-wandb-value.outputs.WANDB_VAL }}"
          WANDB_REPORT_URL: "${{ steps.create-report.outputs.WANDB_REPORT_URL }}"
        
          
